config/routes.rb
Rails.application.routes.draw do
  get 'home/meetme'
  get 'home/speaking'
  get 'home/audio'
  get 'home/testimonials'
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def meetme
  end

  def speaking
  end

  def audio
  end

  def testimonials
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<div class=”main-container”>


<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">


   <!-- Clickable image for link-->
    <a class="navbar-brand" /a>
    <%= link_to image_tag("Aaronmug.png"), root_path, class:"nav-link" %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent"> 

<!--
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>     -->


<h3>       

       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item px-3">
          <%= link_to "Meet Me", home_meetme_path, class:"nav-link" %>
        </li>        

       <p style="color:grey">
      <%= "|" %>
    </p>        


       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item px-3">
          <%= link_to "Speaking", home_speaking_path, class:"nav-link" %>
        </li>

       <p style="color:grey">
      <%= "|" %>
    </p>        
  

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item px-3">
          <%= link_to "Audio", home_audio_path, class:"nav-link" %>
        </li>
        
 <p style="color:grey">
      <%= "|" %>
    </p>        

    
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item px-3">
          <%= link_to "Testimonials", home_testimonials_path, class:"nav-link" %>
        </li>

         
     </div>
      </ul>



       <form class="d-flex">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <form class="d-flex">
          <li class="nav-item px-4">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">(Please Don't)
          Contact</a>
  </form>
</h3>  
    <!--
    </ul>
        <input class="form-control me-2" type="search" placeholder="Try Anyway?" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Fake Search!</button> 
      </form> -->
    </div>
  </div>
</nav>

<br/><br/><br/><br/><br/>




<!--     Bottom Bar   -->



<!-- Remove the container if you want to extend the Footer to full width. -->

<!--  Temporary blocking out this BOTTOM BAR


  <footer class="text-center text-lg-start fixed-bottom" style="background-color: grey;">
    <div class="container d-flex justify-content-center py-5">
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #54456b;">
        <i class="fab fa-facebook-f"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #54456b;">
        <i class="fab fa-youtube"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #54456b;">
        <i class="fab fa-instagram"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #54456b;">
        <i class="fab fa-twitter"></i>
      </button>
    </div>        

    
    <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    
  </footer>
  
</div>
</div>
           -->


<!-- End of .container -->



        </li>
    </div>
</nav>
</footer>

</div> <!-— /.main-container-->

app/views/home/about.html.erb
<h2>About Us</h2>

app/views/home/audio.html.erb
<h4>Welcome to the Aaron Gautreau audio experience:</h4>
<br/><br/>

<%= image_tag("aaronaudio.png") %><br/><br/>

<p>
When I decided to amputate my leg, I was shocked by how far advancements in artificial limbs have come. Long gone were the days of wooden legs. But I was stunned by how much red tape an amputee had to go through actually to get a decent prosthetic. I lost my right leg in March 2007 and have fundraised well over $150,000 to walk. On the AaronGautreau Audio Experience, you'll hear episodes of my life journey, the successes of other amputees, and keynote speeches on motivation and encouragement. I will also interview successful people in business and sports in a way to help you reach your full potential.
<br/><br/><br/><br/>
SUBSCRIBE HERE:</p>

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row">


<div class="column">  
<div class="card" style="width: 18rem; float: left">
  	<%= image_tag("logan1.jpg") %>

  <div class="card-body">
    <h5 class="card-title">Das WEBPAGE!</h5>
    <p class="card-text">Logan is a budding webpage designer, a bootstrap and ruby on rails enthusiast.</p>
    <a href="#" class="btn btn-primary">Go.. Nowhere?</a>
  </div>
</div>


      <div class="row">
     <div class="column">   
    <div class="card" style="width: 18rem; float: right">
    <%= image_tag("aaron1.jpg") %>

  <div class="card-body">
    <h5 class="card-title">LEAFS NEWS!</h5>
    <p class="card-text">Another season is upon us. Will the Leafs build another cup-worthy team to exit in the first round?</p>
    <a href="#" class="btn btn-primary">Find Out!</a>
  </div>
</div>
</div>
</div>
</div>
</div>
</div>



<br/><br>

app/views/home/meetme.html.erb
<h4>The Man, the Legend!</h4>

<br/><br/>
 
 <p> Aaron is a hardcore ballah straight outta Petitcodiac NB. He traveled to Ontario where he hustled mad paper, and made connections with powerful people. He originally left his hometown because he was frequently harrassed by his various harems across the maritimes.</p>

 <p>
 Also:
 </p>	

<p>	Aaron Gautreau is a motivational speaker and childhood cancer survivor who inspires you to be the master of your fate, no matter the circumstance. Since Aaron was a young boy, tens of thousands of people have enjoyed the warmth, humor, and transformational power of his speeches. Aaron has conquered many obstacles in his life. He wasn't supposed to survive stage four cancer when he was diagnosed as a two-year-old.  Aaron was told he wouldn't be able to walk. He eventually amputated his leg in 2007 and has since raised well over $100,000 to walk with a special microprocessor leg. </p>



	<%= image_tag("aaronmeetme1.png") %>



<br/><br/><br/>
<p>
Aaron learned early in his life that circumstances don't define you; You do. He wants to show people how to get through difficult times and how to overcome obstacles and barriers in life. He wants to ignite indefinable confidence in people to know they have the power get through any adversity or circumstance. Aaron also wants to be a voice for amputees. He wants to raise awareness about the lack of funding and rep tape individuals have to go through to get a limb.</p>

<br/><br/><br/>
<p>
Aaron Gautreau always had a passion for radio and television. He graduated from Loyalist College in Belleville Ontario with a journalism and broadcasting degree. He is best known for serving as the morning news anchor for the myFM network in Ontario from 2011-2019. Aaron also has experience working with Rogers Television and Global News. He is also the official spokesperson for Annaleise Carr -- who set a world record by becoming the youngest person (14) to swim across Lake Ontario. Carr later had a successful Lake Erie crossing and raised more than $500,000 for Camp Trillium, which offers year-round recreational experiences to bring children with cancer and their families together.</p>

<br/><br/><br/>

<%= image_tag("aaronmeetme2.png") %><br/>
<br/> 

<p>

Aaron grew up in Petitcodiac, NB. Today, he lives in Simcoe, Ontario. Aaron loves spending his summers near the lake or ocean and enjoys working out and watching the Toronto Maple Leafs destroy the Montreal Canadiens.</p>

<br/> <br/>

<%= image_tag("aaronmeetme4.png") %><br/><br/>



<p>At age two, I was diagnosed with a stage four cancer called Rhabdomyosarcoma. It's cancer that attacks your muscle cells.</p>

<br/> 

<p>I had less than a fifty percent chance to live. I spent two and a half years on chemotherapy and radiation treatments.</p>

<br/>

<p>Doctors declared me cancer free at 5.</p>

<br/><br/><br/>

<%= image_tag("aaronmeetme3.png") %><br/><br/>



<p> I amputated my leg in March 2007. Several complications from cancer and fractured femurs made it too difficult to walk. Cancer also took my right quadriceps muscle.</p>

<br/> 

<p> When I amputated my leg there was no guarantee I would walk again. Because I have no muscle in my leg, I require a microprocessor knee.</p>

<br/> 

<p>Sadly, Canadian health plans and insurance companies provide little coverage, if at all, for these limbs. Since 2007, I have fundraised well over $100,000 to walk. I never want to fundraise again.</p> 

<br/> 

<p>My mission is to increase awareness and change for amputees. </p>
<br/><br/><br/>

<%= image_tag("aaronaudio.png") %><br/><br/>



<p>Television, radio & voiceover professional.</p>

<br/> 

<p>A longtime news anchor on the myFM radio network which spreads across Ontario, Canada.</p>

<br/> 

<p>I also emcee.</p>

<br/><br/><br/>

<%= image_tag("aaronmeetme5.png") %><br/><br/>


<p>I am a motivational speaker who has inspired audiences throughout Canada.</p>

<br/> 

<p>In my speeches I share personal and heartfelt stories to inspire people to discover who they are, and the importance of not giving up.</p>

<br/> 

<p>You have just one life.</p> 

<br/><br/>

app/views/home/speaking.html.erb
<h2>Motivational Speaking</h2>
<br/><br/>


<p>Hi! I'm Aaron Gautreau.</p>
<%= image_tag("aaronmeetme1.png") %>
<br/> 

<p>If you're looking for someone, who can motivate and bring major, and significant change, look no further. My message is relatable, actionable, and genuine – and it’s changing lives.</p>

 <br/>

<p>Whether you are trying to motivate your sales team or students at your school,  I will not only inspire your audience to change, but I’ll also teach them how with proven principals.</p> 

 <br/>

<p>If you are interested in learning more, I would love to speak to you.</p>

app/views/home/testimonials.html.erb
<h1>Hear what people have to say!</h1>
<br/>
<p>"Aaron Gautreau is one of the most inspirational men I know. Aaron’s passion and drive for success are like no other and is extremely inspiring. I had the pleasure of working with Aaron on various occasions. He has supported me always in my acting and music endeavors and had interviewed me countless times and has always supported me in everything I have done in my career. Aaron graciously came and spoke at my holiday concert this past December, and he was a highlight for my entire audience. I cannot begin to count the amount of people that came up to me after the concert and told me how much they loved Aaron and how moving he was. Aaron’s story is insanely talented and motivating, and I am so thankful to know Aaron and have him in my life. GO AARON!!!"

<br/> <br/>

<p>-Kolton Stewart</p>

<p>Canadian TV actor, musician, dancer and songwriter</p>

<br/><br/>

	<%= image_tag("aarontest1.png") %><br/><br/>

<p>"We were very pleased to have Aaron Gautreau as the guest speaker for our Terry Fox Day event.  Aaron’s honesty regarding his cancer diagnosis and the subsequent choices he faced was very moving.  The fact that Aaron faced these challenges as a child and a teenager was very meaningful to the audience that he was presenting to.  The hard choices  Aaron was faced with throughout his adolescence and into his early adulthood hit home to our clients.  His positive and courageous outlook in the face of these challenges was an inspiration to all who heard his story.  Aaron’s resilient attitude of gratefulness and positivity was a reminder to all of us to live in the moment, be thankful for all that we have, and to not let life’s circumstances limit our outcomes."</p>

<br/>

<p>- Joshua Delegarde </p>

<p>Sprucedale Youth Centre</p>

<p>Youth Centre Deputy Administrator, Programs</p>

<br/><br/>


<p>"You had all the kids attention, and I know they walked away feeling inspired!"</p>

<br/>

<p>- Merisa Kriwez</p>

<p>Norfolk County's Recreation Programmer</p>
<br>

	<%= image_tag("aarontest2.png") %><br/><br/>

<p>"Aaron Gautreau walks the talk and models bravery and perseverance with every step.  Aaron’s very presence is an inspiration to overcome obstacles.  Getting up in front of an audience of 250 elementary students, Aaron shared his story with our school.  He is a masterful storyteller who had them mesmerized and in awe, but also moments of laughing out loud at some of the hilarious situations he has gotten himself into with his battery-powered leg. Aaron’s warm and playful nature was a hit with students of all ages. He was fearless about showing them the tricks he can do with his prosthetic leg and fearless about sharing his own battles with anxiety and depression.  In the classroom chats afterward, Aaron handled more specific questions from the students with age-appropriate responses that satisfied their curiosity and inspired all of them to find their courage and face their own fears and obstacles."</p>
 
<br/>

<p>- Heather</p>

<p>Elementary Teacher</p>

<p>Grand Erie District School Board</p>

<br/><br/>

	<%= image_tag("aarontest3.png") %><br/><br/>

<p>"A few years ago, Caledonia Centennial Public School had the privilege of listening to Aaron Gautreau’s story minutes before commencing their annual Terry Fox Run. While Aaron shared his journey of overcoming cancer, the gym was silent. It was evident that both students and staff were fully captivated by his story. The kids loved that Aaron was open to hanging out during the run to answer questions and sign autographs.</p> 

<br/>

<p>I think Aaron’s message of dreaming big and never giving up, regardless of your circumstances is inspirational for all ages.</p>
<p>Best of luck as you continue your journey."</p>

<br/>

<p>- Emily Kekes</p>

<p>E-C-E</p>

<p>Caledonia Centennial Public School</p>

<br/><br/>



<p>"I cannot thank you enough. Today, you changed the way I think about myself and the struggles I have. This is going to stay with me for the rest of my life. Thank you so much."</p>



<p>- Chloe</p>

<p>Student</p> 

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!--  Font Awesome for Icons, etc -->
    <script src="https://kit.fontawesome.com/f2a5e2ffb6.js" crossorigin="anonymous"></script>

    

    <title>Motivational Speaking | Aaron Gautreau</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">

      <br/>
        <h1 class="display-4">Official site of Aaron Gautreau!</h1>
  <p class="lead">Home of Aaron Gautreau, designed by Logan Howatt</p>
  <hr class="my-4">
    <br/>
    <%= yield %>



  </div>



  <footer class="text-center text-lg-start" style="background-color: darkgrey;">
    <div class="container d-flex justify-content-center py-4">



      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color:blue;">
<a href="https://www.facebook.com/aaron.gautreau.5" target="_blank" class="fab fa-facebook-f fa-3x" style="text-decoration: none; color: white"></a>      </button>


      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color:red;">
<a href="https://www.youtube.com/channel/UCvr99lOQLQdOc4hjCebhFjQ" target="_blank" class="fab fa-youtube fa-3x" style="text-decoration: none; color: white"></a>      </button>


      <button type="button" a class="btn btn-primary btn-lg btn-floating mx-2" style="background-color:deeppink;">
<a href="https://instagram.com/aarongmotivation" target="_blank"class="fab fa-instagram fa-3x" style="text-decoration: none; color: white"></a>    </button>

      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color:skyblue;">
<a href="https://twitter.com/Gautreau89" target="_blank" class="fab fa-twitter fa-3x" style="text-decoration: none; color: white"></a>    </button>
    </div>        

    
    <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2021 Not fuckin Copyright:
      <a class="text-white" href="#">Dontvisit.com</a>
    </div>
    
  </footer>





  

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>